runtime: nodejs20
env: standard

instance_class: F2

env_variables:
  PORT: 8080
  GOOGLE_CREDENTIALS: |
    {
      "type": "service_account",
      "project_id": "excelapi-454722",
      "private_key_id": "acc195c842874ca7cf47a12bdeb0719fcc5768a7",
      "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDJ/IpSahMpOyad\nGskDlHOvbpYLBNrtvaCJi5m9AWSf00iuTxE3Mx9sG6p47SBxU3gLgwrkJpxqDmLS\nzHiCwutVfZ+1yPk4OFRy8tNYUk1/qYMqbm85dGG1+mAtW0QvBA5mrSMgAmXiRxFM\ncucDHzgd01UD79MpW4GC6kH/UcJNCOaguoxA5sNlVLkHSvHh9jczRtUuOehOvnUT\n/0IuaNh2qkCpXI4hVW5XA3ym+aKRtMaDdjOIGHUW8KDq9LaDd1U4Vyb357hpJZL6\nHG/q5jEUw4cmSW52N6VJqAO5P/CFbM8p7bTOirzlXMn+FEIvZ7+BYybYTo9Unb03\nwCALZlFxAgMBAAECggEAFXFzh9NODHMEouoci/4/F9FAKZRO361hdSi2XgvfUF5g\nWWz4cWlCfTokq2jVKGLJnENBrT3yHgo/8IwXgR5LWIyZH3XiC1djk752tGosYxCu\nZZtKwIk79FNL0ZTeVLV0B+96iqPmiBKuYfTS1JCEZxov7NaRjtLxmWHgNshJvd6y\n/0DHSIw/FXzPccILX2KyIiURIyt6jKA/lpaaQLboM0pfrHVyh1bsdwlaGURwFZJt\nVIAWXZk3JdmCT68kCVb9n8HRryPFaQ/YMFcXCAh6K2KJ69/U32WEYuU6OmITW1W4\n1YaB+OQEGhpYSOMBLZZegVwOf5BbkCSjNDXT6W6KYQKBgQD8Gtq4tR/HAElefmqa\nyOs5U+4I++sSBaZ/nDUZc5HVn/d+jtZnjmpglB0lnAmmex+2YfaXvJLREeXTrKxX\nBaq4ks/dCw6SRCJoSadIQiP0OMFAzH2VfjYCda8eIambVHc91nYXBW357NKnrNXI\nm/Dkl/JTTxdF57toTnhbx8BG2QKBgQDNG3QbsEuI0ESzba90GD/UD51DLqk3KZYV\naW7EP/ngmAP77s6semVsEWPOLhM9V+3xy9MjREeYdrbLELbN9/UDki0uLvOoZ4ct\nZ8Ja7aNqI/jOqQ+5kwuiQstI/UIxTRq5Z6ewWjHdG/ThRiPHItobEtncxF5zQtH7\nZSFsBU0wWQKBgAJ1RJKueWvYTd7U/rcZpGl/rv95bVZUpcXywPXJka9yitg6Dk8e\nLV1ZtFsMhW+RHcMKe3wJQ6k0Mnh444lJrdt02v/9vpugfHFl3nKu6mjUMNYv6D2P\n6HjnqthxXZT9ItiAgdBBpkvcikVGQyNcmeGwtZUoXUK6OrKOqU/Dx9UpAoGACHjQ\n0+/1PsJzhAHM1HvH7ydx9Htx6+Bg3aOMOrj1xkwhJf/YM5GerNcPC04l50vBfVJQ\n90zztB17MWoQUvOiADLCgPzZfaRBFiQKCB12uYSg21BqYNztBxfBM9OaL1Ui/HOG\nnqcrFhn4hHGUOr56ydF+hDrsN9CTwdGMjtytMokCgYEAtNeoPu/oBGM1uWEJU8st\nTSM6xwAlRtwvMx2z2hlTrp2492/wVLr/cV7/20UHt2KiHK6HXUldrC9WnfIW9KE+\nnD0yEMpSBqrL07eEYlKjDOANPISiZ5ax8FWc0Mb4JYGkkUnTlQQbBWzrTMZoTTFT\nCbqkImWM2XaTDOewjIMyW2g=\n-----END PRIVATE KEY-----\n",
      "client_email": "excelapi-454722@appspot.gserviceaccount.com",
      "client_id": "116802424616458683102",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/excelapi-454722%40appspot.gserviceaccount.com",
      "universe_domain": "googleapis.com"
    }
  GRADE_1: "1tXJ_ro0Cbn_HWioRYqAEypnID57OemTq"
  GRADE_2: "1cJIMCEu8igF01mNk64sBdbwiPqAv4P1B"
  GRADE_3: "1--pBh9WbrWZUPzGSoHpeQ1bzMi1RRRpw"
  GRADE_4: "1XwXV3HO0onXZ6ZgHpgrMrnZyh-fH6zlC"
  GRADE_5: "1HXGS6EbKrS5318WriibTG7n62laaoGam"
  GRADE_6: "1gxM2lz7T2TovXEMaLtPqT4sHumorGCgV"

handlers:
  - url: /public
    static_dir: public

  - url: /.*  
    script: auto

#gcloud app deploy