runtime: nodejs20
env: standard

instance_class: F2

env_variables:
  PORT: 8080
  GOOGLE_CREDENTIALS: |
    {
      "type": "service_account",
      "project_id": "excelapi-454722",
      "private_key_id": "42c2bee22cff9d10411361bb28de07dea659f6c7",
      "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDKuHpEX3UfR7J3\nObE31AnT16E2BXFvwrfznd2uoIy6/P2FE0IDgNEb3aUbsY1MtQ1Ce6UJEKTO2g3T\niljMdIWtFWQ6sHfH5c6SckioBtgpgunGAsrf0DBlvlS5jrOcRvUDr0cVrWIyGtOR\nyEeMzxF4nV4uk1ETVdomiD38WwEQ9wWDySEwYxv+pYnXeEA9eT6Y6Aev4fxWrJX3\nk5qtsuNd16uYCATHoVJCUPQGGJnHsR8Zu/XTXSIz8qWd2K11tWR+YTP7lbliVFp6\nDcj9ovaRaFZEnir7HgN0+1nHcdjV9QHZg0YgpuFbpex4xOyln7TxTdcjco48nrY/\nJN4EmdC9AgMBAAECggEAAbGzQsVLyZWbOS5Z4u8Gyo3nL/gU9DD0s4pcZbfmYL0d\ndg0Mu7W0vwBX1OwcdzesBPI+hwg6RUG4FpVnmC9g/rkcZ1m2sMWBMLEta+CBNedg\nwmAfGU2RTDKZB7iDRiPucft3NOuyt00zs++3Wnilwl6mFfxkd0HtuQoaYrvC9rbJ\n9B7oyl1BFo/YSrm3+q1T+YRj6V98r7kn7RO1Z6QHlEmflui7ZhXMUuuMDQXyxZai\n+xaOg7IziK+1kbbhv4wr98BE8Vcqtqk8vgHHXoZZv+EwK6Z3LFkE6HPllfuKOFFa\nJQRtylpWBkTM9pf1FXNCdPMVLZazs3ctMaQXLuaviQKBgQD1QzDOfitOC8hDosU3\njkZlotCl5Wp74f63fnyj3jb6oohUog1qrNEgb4ufaRN/qTINe1pfyvTUcSDAJymm\neL/F21jV6E2PAUvyA69RMsd8UEJWIG/L1TbvTbIHfvmOPR2ljB6rrpXbRTiyA8Bs\n+WcEFdNkYgy0nMM4y3HK0of1CQKBgQDTmH5y8x2c04o72dWXgIjLMWmC5/lm73Lx\nq8EPL7lZX3w3ib06ElwVs9N1F3uVV+oJCQZhIsfISfh7OkEf5d9zBYvT9ILdm9vu\nnOUWzhDAWY+c1udDsmaC4PeIK4JjkPp1zGeCuPNPNwG0oaQJpFk+2nkabMzRgl0Y\nzz6dg9m/FQKBgBswLJvnbqODONsOkzA6bGFd8CVDzk8XWWY79lMwEgYsuFIxeK1H\npRMkamTsgAXZ2ruV3gnadNOMCuZiMQLMRe4IB8wGqXpd2W5lrCyjJWwJdaEYjWwa\nIbHbeg3MrJtw+PVeGBROETyyaruJIO6zoxDX3ow1NlVbP2TvYJjsR7gJAoGAV3Ug\nTsLN6pRE/pf7ALPP1qyFv+XB4Bn4mIs1MOG46ofc/9eervIHvbCmJi+elQvRYAqq\n6FtH2DE60zQw1s5cnV4dfW4C6TYSoX2X8uUZZ2edRGZPEFwcotv5c/8H1b+GxknG\nPvHTH1rNCawF8TZM7P3AMHvn7HDFqgt/BfwJdEECgYEArlVCcnI2C2Ll+PAsjiwy\nksE80o8+HK2WRMS5kQh4rhUBmlgUmIiFc9z0/UGOqiPJ8upWS5GnmHcS/EZbWEd0\nIlu7HmM3PzG3fpWRk37RrxXUYkrVwSX8ASmCtptgveSfmlgDJ11/2qDk8dIDfo0K\nO8GoAxrm7H4MOVoUQAOTYzM=\n-----END PRIVATE KEY-----\n",
      "client_email": "san-pedro@excelapi-454722.iam.gserviceaccount.com",
      "client_id": "116172624570671444345",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/san-pedro%40excelapi-454722.iam.gserviceaccount.com",
      "universe_domain": "googleapis.com"
    }
  GRADE_1: "1tXJ_ro0Cbn_HWioRYqAEypnID57OemTq"
  GRADE_2: "1cJIMCEu8igF01mNk64sBdbwiPqAv4P1B"
  GRADE_3: "1--pBh9WbrWZUPzGSoHpeQ1bzMi1RRRpw"
  GRADE_4: "1XwXV3HO0onXZ6ZgHpgrMrnZyh-fH6zlC"
  GRADE_5: "1HXGS6EbKrS5318WriibTG7n62laaoGam"
  GRADE_6: "1gxM2lz7T2TovXEMaLtPqT4sHumorGCgV"

handlers:
  - url: /public
    static_dir: public

  - url: /.*  
    script: auto

#gcloud app deploy